### ISSUE TITLE
Code Proposal: Allow User to Specify Sheet (Work with multi-sheet Excel Files)

### ISSUE THREAD

**Issue by bai-yi-bai** [Pytlicek/sheet2dict#1]
This library is awesome! I'm using it a lot since it makes working with Excel files very simple.

I have a proposal: Allow the user to specify the sheet they want to modify. 

I write a lot of functional programming and I can't remember if it's possible to overwrite a class function at import, so instead I've modified the sheet2dict to return a specified sheet when openpyxl opens the file.

in main.py:
```python
def xlsx_to_dict(self, path, select_sheet=None):
        """
        Read a Worksheet and return it as array of dictionaries
        :param self: Worksheet Object
        :param path: Path to XLSX file
        :return: Array of rows as dictionaries
        """
        book = load_workbook(path)
        if select_sheet == None:
              sheet = book.active
        else:
              sheet = book[select_sheet]
```

The user would then read an Excel file like this:
```python
ws =Worksheet()
ws.xlsx_to_dict(path=<insert path>, select_sheet='<sheetname>'
```

I don't know if this is the most elegant way to select a sheet, but it works for me. 
I suppose to import all worksheets by default - I think the maximum is 32 - into a larger dictionary, <edit I didn't complete my thought>, that there could be a clever way to put dictionaries in dictionaries, but this might be too convoluted since I assume most users will just use one sheet.</edit>
Another option is just to continue creating Worksheet() objects with different names and sheets selected.

**Comment by Pytlicek** [comment]
Actually, this is a good idea @bai-yi-bai! I also thought about it a long time ago :)  
I think the style in which you wrote the example code is fine 👍  
I tested it and this way we wouldn't break anything in the code ⚡️
If you want to do PR, please do it and we can then merge it into sheet2dict.
Many thanks 🙏

![Screenshot 2021-07-09 o 19 45 47](https://user-images.githubusercontent.com/1430522/125117906-2f483900-e0ef-11eb-9bd2-6b6d8ed5db1a.png)

**Comment by bai-yi-bai** [comment]
Cool! 

I also created another test Excel file for testing and everything looked fine. I think I created the pull request correctly from PyCharm/Github on my personal PC. I'm excited to replace the version on my work PC.

BTW, I found my way here from the post on HackerNews a few weeks ago.

**Comment by Pytlicek** [comment]
@bai-yi-bai thank you very much for your contribution to the sheet2dict 🙏  

There is a new version https://github.com/Pytlicek/sheet2dict/releases/tag/0.1.0 released on PyPi with your changes: https://pypi.org/project/sheet2dict/  

Thanks again and keep up the great work and contributions to the Open-Source Software 👍
